version: "3.7"
services:
  app:
    build:
      args:
        user: sidnei
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-acl-app
    container_name: laravel-acl-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-acl
    depends_on: 
      - db
  db:   
    build:     
      context: ./
      dockerfile: DockerfileDB
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel-acl-db
    restart: unless-stopped    
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USERNAME}"     
    volumes:     
       - ./docker-compose/db:/var/lib/mysql 
    networks:
      - laravel-acl
  nginx:
    image: nginx:alpine
    container_name: laravel-acl-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-acl
networks:
  laravel-acl:
    driver: bridge